from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.api.deps import get_current_user
from app.repositories.scenario_repo import ScenarioRepository
from app.models.user import UserRecord

router = APIRouter(prefix="/export", tags=["Export"])

@router.get("/navigator/{scenario_id}")
def export_mitre_navigator_layer(
    scenario_id: str,
    db: Session = Depends(get_db),
    current_user: UserRecord = Depends(get_current_user)
):
    """
    Ekspor skenario ke format JSON layer MITRE ATT&CK Navigator.
    Ini 100% additive dan hanya membaca data (read-only).
    """
    repo = ScenarioRepository(db)
    scenario = repo.get_scenario(scenario_id, current_user.id)
    
    if not scenario:
        raise HTTPException(status_code=404, detail="Skenario tidak ditemukan")

    cir_data = scenario.cir_graph_data
    if not cir_data or "attack_graph" not in cir_data or "nodes" not in cir_data["attack_graph"]:
        raise HTTPException(status_code=400, detail="Data graf CIR tidak lengkap")

    techniques_map = {}
    
    # Ambil nodes
    nodes = cir_data["attack_graph"]["nodes"]
    for node in nodes:
        tech_id = node.get("technique")
        if tech_id and tech_id.startswith("T"):
            # Jika sudah ada di map, kita bisa append komentar atau step_id
            step_id = node.get("step_id", "?")
            tech_name = node.get("technique_name", "")
            
            if tech_id not in techniques_map:
                techniques_map[tech_id] = {
                    "techniqueID": tech_id,
                    "color": "#e60d0d", # Merah sebagai indikasi ancaman
                    "comment": f"Steps: {step_id}",
                    "enabled": True,
                    "showSubtechniques": True
                }
            else:
                techniques_map[tech_id]["comment"] += f", {step_id}"

    layer = {
        "name": f"ThreatCanvas - {scenario.name or scenario_id}",
        "versions": {
            "attack": "14",
            "navigator": "4.9.1",
            "layer": "4.5"
        },
        "domain": "enterprise-attack",
        "description": f"Generated by ThreatCanvas for scenario ID: {scenario_id}",
        "techniques": list(techniques_map.values()),
        "gradient": {
            "colors": ["#ff6666", "#e60d0d"],
            "minValue": 0,
            "maxValue": 100
        },
        "legendItems": [
            {
                "label": "Threat Actor Techniques",
                "color": "#e60d0d"
            }
        ]
    }

    return layer
